=== Hegoi-Elorrieta/MARKATZEKO-LENGUAIAK/Hegoi Vazquez/4_Erronka/XML/ikasleak10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Datu moten definizioa-->

<xs:simpleType name="mugikorrazbk">
    <xs:restriction base="xs:integer">
        <xs:totalDigits value="9"></xs:totalDigits>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="herrikaraktere">
    <xs:restriction base="xs:string">
        <xs:maxLength value="50"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nandigitoak">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

<xs:complexType name="familia">
    <xs:sequence>
        <xs:element name="izena" type="xs:string"></xs:element>
        <xs:element name="telefonoa" type="xs:integer"></xs:element>
    </xs:sequence>
</xs:complexType>

<!--Datu moten definizioa amaitu-->

<xs:complexType name="helbidedatua">
    <xs:sequence>
        <xs:element name="kalea">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="herrikaraktere">
                        <xs:attribute name="mota">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="kalea"></xs:enumeration>
                                    <xs:enumeration value="errepidea"></xs:enumeration>
                                    <xs:enumeration value="bidea"></xs:enumeration>
                                    <xs:enumeration value="plaza"></xs:enumeration>
                                    <xs:enumeration value="etorbidea"></xs:enumeration>
                                    <xs:enumeration value="zeharbidea"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
        <xs:element name="zbk">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"></xs:minInclusive>                    
                    <xs:maxInclusive value="1000"></xs:maxInclusive>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="herria">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="herrikaraktere">
                        <xs:attribute name="postaKodea" type="xs:integer"></xs:attribute>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
        <xs:element name="probintzia" type="herrikaraktere">
        </xs:element>
    </xs:sequence>
</xs:complexType>
    <xs:element name="ikasleak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ikaslea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izena" type="xs:string"></xs:element>
                            <xs:element name="helbidea" type="helbidedatua"></xs:element>
                            <xs:choice>
                                <xs:element name="telefonoa" type="mugikorrazbk"></xs:element>
                                <xs:element name="mugikorra" maxOccurs="3" type="mugikorrazbk"></xs:element>
                            </xs:choice>
                                <xs:element name="eposta" type="xs:integer" minOccurs="0"></xs:element>
                                <xs:choice minOccurs="0" maxOccurs="2">
                                    <xs:element name="ama" minOccurs="0" maxOccurs="2" type="familia"></xs:element>
                                    <xs:element name="aita" minOccurs="0" maxOccurs="2" type="familia"></xs:element>
                                </xs:choice>
                                <xs:element name="elbarritasuna" minOccurs="0">
                            <xs:complexType>
                                    <xs:attribute name="gradua" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="\d{2}%"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                            <xs:attribute name="nan" use="required" type="nandigitoak"></xs:attribute>
                            <xs:attribute name="errepikatzailea" type="xs:boolean"></xs:attribute>
                            <xs:attribute name="jaiotze-data" type="xs:date" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hegoi-Elorrieta/MARKATZEKO-LENGUAIAK/Hegoi Vazquez/4_Erronka/XML/Ikasleak10.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ikasleak10.xsd">
    <ikaslea nan="11111111L" errepikatzailea="false" jaiotze-data="2005-11-17">
        <izena>Iraide Etxeberria</izena>
        <helbidea>
            <kalea mota="etorbidea">Kale nagusia</kalea>
            <zbk>5</zbk>
            <herria postaKodea="48004">Bilbao</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <telefonoa>944000000</telefonoa>
    </ikaslea>
    <ikaslea nan="22222222L" errepikatzailea="false" jaiotze-data="2005-11-17">
        <izena>Joseba Mikel Zarraga</izena>
        <helbidea>
            <kalea mota="etorbidea">Gorbeia</kalea>
            <zbk>75</zbk>
            <herria postaKodea="48001">Artea</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <mugikorra>944999999</mugikorra>
        <mugikorra>666777888</mugikorra>
        <ama>
            <izena>Marisa</izena>
            <telefonoa>999444333</telefonoa>
        </ama>
        <aita>
            <izena>Iñaki</izena>
            <telefonoa>999444332</telefonoa>
        </aita>
        <aita>
            <izena>Iñaki</izena>
            <telefonoa>999444332</telefonoa>
        </aita>
        
    </ikaslea>
</ikasleak>
