=== Hegoi-Elorrieta/MARKATZEKO-LENGUAIAK/Hegoi Vazquez/4_Erronka/XML/ikasleak07.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Datu moten definizioa-->

<xs:simpleType name="mugikorrazbk">
    <xs:restriction base="xs:integer">
        <xs:totalDigits value="9"></xs:totalDigits>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="herrikaraktere">
    <xs:restriction base="xs:string">
        <xs:maxLength value="50"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nandigitoak">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

<!--Datu moten definizioa amaitu-->

<xs:complexType name="helbidedatua">
    <xs:sequence>
        <xs:element name="kalea">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="herrikaraktere">
                        <xs:attribute name="mota" type="xs:integer"></xs:attribute>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
        <xs:element name="zbk">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"></xs:minInclusive>                    
                    <xs:maxInclusive value="1000"></xs:maxInclusive>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="herria">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="herrikaraktere">
                        <xs:attribute name="postaKodea" type="xs:integer"></xs:attribute>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
        <xs:element name="probintzia" type="herrikaraktere">
        </xs:element>
    </xs:sequence>
</xs:complexType>
    <xs:element name="ikasleak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ikaslea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izena" type="xs:string"></xs:element>
                            <xs:element name="helbidea" type="helbidedatua"></xs:element>
                            <xs:choice>
                                <xs:element name="telefonoa" type="mugikorrazbk">
                                </xs:element>
                                <xs:element name="mugikorra" maxOccurs="3" type="mugikorrazbk">
                                </xs:element>
                            </xs:choice>
                            <xs:element name="eposta" type="xs:integer" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="nan" use="required" type="nandigitoak">
                        </xs:attribute>
                        <xs:attribute name="errepikatzailea" type="xs:boolean"></xs:attribute>
                        <xs:attribute name="jaiotze-data" type="xs:date" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hegoi-Elorrieta/MARKATZEKO-LENGUAIAK/Hegoi Vazquez/4_Erronka/XML/Ikasleak07.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ikasleak07.xsd">
    <ikaslea nan="11111111L" errepikatzailea="false" jaiotze-data="2005-11-17">
        <izena>Iraide Etxeberria</izena>
        <helbidea>
            <kalea mota="2">Kale nagusia</kalea>
            <zbk>5</zbk>
            <herria postaKodea="48004">Bilbao</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <telefonoa>944000000</telefonoa>
    </ikaslea>
    <ikaslea nan="22222222L" errepikatzailea="false" jaiotze-data="2005-11-17">
        <izena>Joseba Mikel Zarraga</izena>
        <helbidea>
            <kalea mota="1">Gorbeia</kalea>
            <zbk>75</zbk>
            <herria postaKodea="48001">Artea</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <mugikorra>944999999</mugikorra>
        <mugikorra>666777888</mugikorra>
    </ikaslea>
</ikasleak>
